### PR TITLE
Compatibility for Odoo 9.0

### PR DESCRIPTION
**Pull request by ryanc-me**
Hey @lukebranch,

Hopefully this what you meant! I've just double-checked, and everything is working well under Odoo v9. I also changed the folder structure slightly, I think having `__opererp__` and `__init__` in the root folder makes the module _much_ easier to handle for both developers and end-users.

Let me know what you think!

### CODE REVIEW

**Comment by lukebranch** [comment]
@MGinshe ,

Thanks! I'll pull and review it now and get back to you with my comments.

**Comment by ryanc-me** [comment]
Hey @lukebranch,

I was just wondering where you're at with the PR?

**Comment by lukebranch** [comment]
@MGinshe ,

Sorry, I still have not yet had the chance to review it. I'm planning to review and merge on Sunday (Hong Kong Time) if I don't discover any issues.

**Comment by lukebranch** [comment]
@MGinshe ,

I've taken a look and it all seems to be fine. I have only one comment at the moment after a quick review, there seem to be some typos here:



these should be 'multi' not 'mutli'. If you get the chance it would be great if you could update the README.md file for the 9.0 branch as well (clone instructions, etc.).

Once i've heard back from you i'll merge. Thanks for the PR!

**Comment by lukebranch** [comment]
@MGinshe ,

I'll merge this for now and we can make improvements later, thanks for the PR!

**Pull request merged**
